security:
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:             crm_site_user_provider
                csrf_provider:        form.csrf_provider
                default_target_path:  /
                always_use_default_target_path: false
            logout:
                target:   /
            anonymous:    true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: ROLE_USER }
